import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeContextProvider } from "./context/theme";
import { Toaster } from "react-hot-toast";
import CartSection from "@/components/sections/CartSection";
import Backdrop from "@/components/UI/Backdrop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ThemeContextProvider>
          {/* <Backdrop /> */}
          <CartSection />
          <main className="z-0">{children}</main>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
